//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.8.2
//     from Assets/Settings/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;
using UnityEngine;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Global"",
            ""id"": ""74f02d9e-0e43-423c-860d-1277e74aae3d"",
            ""actions"": [
                {
                    ""name"": ""VolumeDown"",
                    ""type"": ""Button"",
                    ""id"": ""f5935f86-7449-4747-8e5a-131c59b942ae"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""VolumeUp"",
                    ""type"": ""Button"",
                    ""id"": ""7cda4ef9-834f-4667-83c9-72af7034eeef"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextClip"",
                    ""type"": ""Button"",
                    ""id"": ""31a0d0fe-8102-44ab-a4c7-7b413014bfd6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PreviousClip"",
                    ""type"": ""Button"",
                    ""id"": ""591a9927-d58f-42c3-aa37-b2a1cd0f1070"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Delete"",
                    ""type"": ""Button"",
                    ""id"": ""01e41582-5cb0-4a12-afad-7166f6a418a5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EnableMove"",
                    ""type"": ""Button"",
                    ""id"": ""3e3e30ee-10c6-47e5-868f-493c14a0e975"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EnableHeightAdjustment"",
                    ""type"": ""Button"",
                    ""id"": ""5719a54b-f98b-4281-a4e6-fa4f0af9ba3e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EnableRotate"",
                    ""type"": ""Button"",
                    ""id"": ""37cf6bef-10c5-4aa5-8ed9-a5dd51ff5906"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MultiAction"",
                    ""type"": ""Button"",
                    ""id"": ""07b6a4e9-7784-4f34-961c-b92df5ecc4a8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ba238885-e49d-4849-bbe0-2c93d638c1ac"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VolumeDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11bcf75e-fd1f-4bbf-a29a-5ba9c21d8a64"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VolumeUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32fd042e-3c6f-474d-87f9-54b4c39e65e5"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextClip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""338086b4-c247-41f0-9e7b-a2c93fb91b3f"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PreviousClip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""afe18884-d26a-4625-8824-155a6de09542"",
                    ""path"": ""<Keyboard>/delete"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6723a304-a582-4b72-b069-cc016bef2716"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnableMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2eb71374-5b7f-4bfe-9ab7-ca71810f1d7b"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnableMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eef18a31-d55e-4440-abd2-0387f455fd6f"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnableHeightAdjustment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b54af495-2c52-445b-9c37-ed28af46361d"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnableHeightAdjustment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15a1062f-bac3-4088-97a8-8e0734d48633"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnableRotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0c3ab0d-3f3c-4447-839a-0c47c74a1f63"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MultiAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Global
        m_Global = asset.FindActionMap("Global", throwIfNotFound: true);
        m_Global_VolumeDown = m_Global.FindAction("VolumeDown", throwIfNotFound: true);
        m_Global_VolumeUp = m_Global.FindAction("VolumeUp", throwIfNotFound: true);
        m_Global_NextClip = m_Global.FindAction("NextClip", throwIfNotFound: true);
        m_Global_PreviousClip = m_Global.FindAction("PreviousClip", throwIfNotFound: true);
        m_Global_Delete = m_Global.FindAction("Delete", throwIfNotFound: true);
        m_Global_EnableMove = m_Global.FindAction("EnableMove", throwIfNotFound: true);
        m_Global_EnableHeightAdjustment = m_Global.FindAction("EnableHeightAdjustment", throwIfNotFound: true);
        m_Global_EnableRotate = m_Global.FindAction("EnableRotate", throwIfNotFound: true);
        m_Global_MultiAction = m_Global.FindAction("MultiAction", throwIfNotFound: true);
    }

    ~@Controls()
    {
        Debug.Assert(!m_Global.enabled, "This will cause a leak and performance issues, Controls.Global.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Global
    private readonly InputActionMap m_Global;
    private List<IGlobalActions> m_GlobalActionsCallbackInterfaces = new List<IGlobalActions>();
    private readonly InputAction m_Global_VolumeDown;
    private readonly InputAction m_Global_VolumeUp;
    private readonly InputAction m_Global_NextClip;
    private readonly InputAction m_Global_PreviousClip;
    private readonly InputAction m_Global_Delete;
    private readonly InputAction m_Global_EnableMove;
    private readonly InputAction m_Global_EnableHeightAdjustment;
    private readonly InputAction m_Global_EnableRotate;
    private readonly InputAction m_Global_MultiAction;
    public struct GlobalActions
    {
        private @Controls m_Wrapper;
        public GlobalActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @VolumeDown => m_Wrapper.m_Global_VolumeDown;
        public InputAction @VolumeUp => m_Wrapper.m_Global_VolumeUp;
        public InputAction @NextClip => m_Wrapper.m_Global_NextClip;
        public InputAction @PreviousClip => m_Wrapper.m_Global_PreviousClip;
        public InputAction @Delete => m_Wrapper.m_Global_Delete;
        public InputAction @EnableMove => m_Wrapper.m_Global_EnableMove;
        public InputAction @EnableHeightAdjustment => m_Wrapper.m_Global_EnableHeightAdjustment;
        public InputAction @EnableRotate => m_Wrapper.m_Global_EnableRotate;
        public InputAction @MultiAction => m_Wrapper.m_Global_MultiAction;
        public InputActionMap Get() { return m_Wrapper.m_Global; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GlobalActions set) { return set.Get(); }
        public void AddCallbacks(IGlobalActions instance)
        {
            if (instance == null || m_Wrapper.m_GlobalActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GlobalActionsCallbackInterfaces.Add(instance);
            @VolumeDown.started += instance.OnVolumeDown;
            @VolumeDown.performed += instance.OnVolumeDown;
            @VolumeDown.canceled += instance.OnVolumeDown;
            @VolumeUp.started += instance.OnVolumeUp;
            @VolumeUp.performed += instance.OnVolumeUp;
            @VolumeUp.canceled += instance.OnVolumeUp;
            @NextClip.started += instance.OnNextClip;
            @NextClip.performed += instance.OnNextClip;
            @NextClip.canceled += instance.OnNextClip;
            @PreviousClip.started += instance.OnPreviousClip;
            @PreviousClip.performed += instance.OnPreviousClip;
            @PreviousClip.canceled += instance.OnPreviousClip;
            @Delete.started += instance.OnDelete;
            @Delete.performed += instance.OnDelete;
            @Delete.canceled += instance.OnDelete;
            @EnableMove.started += instance.OnEnableMove;
            @EnableMove.performed += instance.OnEnableMove;
            @EnableMove.canceled += instance.OnEnableMove;
            @EnableHeightAdjustment.started += instance.OnEnableHeightAdjustment;
            @EnableHeightAdjustment.performed += instance.OnEnableHeightAdjustment;
            @EnableHeightAdjustment.canceled += instance.OnEnableHeightAdjustment;
            @EnableRotate.started += instance.OnEnableRotate;
            @EnableRotate.performed += instance.OnEnableRotate;
            @EnableRotate.canceled += instance.OnEnableRotate;
            @MultiAction.started += instance.OnMultiAction;
            @MultiAction.performed += instance.OnMultiAction;
            @MultiAction.canceled += instance.OnMultiAction;
        }

        private void UnregisterCallbacks(IGlobalActions instance)
        {
            @VolumeDown.started -= instance.OnVolumeDown;
            @VolumeDown.performed -= instance.OnVolumeDown;
            @VolumeDown.canceled -= instance.OnVolumeDown;
            @VolumeUp.started -= instance.OnVolumeUp;
            @VolumeUp.performed -= instance.OnVolumeUp;
            @VolumeUp.canceled -= instance.OnVolumeUp;
            @NextClip.started -= instance.OnNextClip;
            @NextClip.performed -= instance.OnNextClip;
            @NextClip.canceled -= instance.OnNextClip;
            @PreviousClip.started -= instance.OnPreviousClip;
            @PreviousClip.performed -= instance.OnPreviousClip;
            @PreviousClip.canceled -= instance.OnPreviousClip;
            @Delete.started -= instance.OnDelete;
            @Delete.performed -= instance.OnDelete;
            @Delete.canceled -= instance.OnDelete;
            @EnableMove.started -= instance.OnEnableMove;
            @EnableMove.performed -= instance.OnEnableMove;
            @EnableMove.canceled -= instance.OnEnableMove;
            @EnableHeightAdjustment.started -= instance.OnEnableHeightAdjustment;
            @EnableHeightAdjustment.performed -= instance.OnEnableHeightAdjustment;
            @EnableHeightAdjustment.canceled -= instance.OnEnableHeightAdjustment;
            @EnableRotate.started -= instance.OnEnableRotate;
            @EnableRotate.performed -= instance.OnEnableRotate;
            @EnableRotate.canceled -= instance.OnEnableRotate;
            @MultiAction.started -= instance.OnMultiAction;
            @MultiAction.performed -= instance.OnMultiAction;
            @MultiAction.canceled -= instance.OnMultiAction;
        }

        public void RemoveCallbacks(IGlobalActions instance)
        {
            if (m_Wrapper.m_GlobalActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGlobalActions instance)
        {
            foreach (var item in m_Wrapper.m_GlobalActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GlobalActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GlobalActions @Global => new GlobalActions(this);
    public interface IGlobalActions
    {
        void OnVolumeDown(InputAction.CallbackContext context);
        void OnVolumeUp(InputAction.CallbackContext context);
        void OnNextClip(InputAction.CallbackContext context);
        void OnPreviousClip(InputAction.CallbackContext context);
        void OnDelete(InputAction.CallbackContext context);
        void OnEnableMove(InputAction.CallbackContext context);
        void OnEnableHeightAdjustment(InputAction.CallbackContext context);
        void OnEnableRotate(InputAction.CallbackContext context);
        void OnMultiAction(InputAction.CallbackContext context);
    }
}
